networks:
  app_net:

services:
  mysql:
    image: mysql:8.0.40
    container_name: ospos-mysql
    restart: always
    expose:
      - "3306"
    networks:
      - app_net
    volumes:
      - ${INSTALL_BASE_DIR}/mysql-data/:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=3TRPgUAm*7LpbE
      - MYSQL_DATABASE=ospos
      - MYSQL_USER=tech
      - MYSQL_PASSWORD=3TRPgUAm*7LpbE

  ospos:
    image: dchristm77/php-apache-ospos:latest
    container_name: ospos-php-apache
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:80"
    networks:
      - app_net
    volumes:
      - ${INSTALL_BASE_DIR}/opensourcepos/:/var/www/:rw
    environment:
      - CI_ENVIRONMENT=production
      - MYSQL_USERNAME=tech
      - MYSQL_PASSWORD=3TRPgUAm*7LpbE
      - MYSQL_DB_NAME=ospos
      - MYSQL_HOST_NAME=ospos-mysql
      - PHP_TIMEZONE=UTC

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    networks:
      - app_net
    environment:
      - PMA_HOST=ospos-mysql
    depends_on:
      - mysql
