services:
  mysql:
    image: mysql:8.0.40
    container_name: ospos-mysql
    restart: always
    expose:
      - "3306"
    networks:
      - lamp_net
    volumes:
      - mysql-data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=pointofsale
      - MYSQL_DATABASE=ospos
      - MYSQL_USER=tech
      - MYSQL_PASSWORD=pointofsale

  ospos:
    image: dchristm77/php-apache-ospos:latest
    container_name: ospos-php-apache
    restart: always
    user: 568:3002
    depends_on:
      - mysql
    ports:
      - "8088:80"
    networks:
      - lamp_net
    volumes:
      - /mnt/CNASV2/Webserver/www/html/:/var/www/html/:rw
    environment:
      - CI_ENVIRONMENT=production
      - MYSQL_USERNAME=tech
      - MYSQL_PASSWORD=pointofsale
      - MYSQL_DB_NAME=ospos
      - MYSQL_HOST_NAME=ospos-mysql
      - PHP_TIMEZONE=UTC

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    networks:
      - lamp_net
    environment:
      - PMA_HOST=ospos-mysql
    depends_on:
      - mysql

networks:
  lamp_net:

volumes:
  mysql-data:
